import{a as f,S as d,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const p="53485925-ce0cf73790b8d8f557c3a40d7",m="https://pixabay.com/api/";async function g(i){const r={key:p,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};return f.get(m,{params:r}).then(e=>e.data)}const l=document.getElementById("gallery"),u=new d(".gallery a",{captionsData:"alt",captionDelay:250}),o=document.getElementById("loader");function h(i){if(!Array.isArray(i)||i.length===0)return;const r=i.map(e=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <div class="card">
          <img class="card-image" src="${e.webformatURL}" alt="${v(e.tags)}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${e.likes}</p>
            <p class="info-item"><b>Views:</b> ${e.views}</p>
            <p class="info-item"><b>Comments:</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
      </a>
    </li>`).join("");l.insertAdjacentHTML("beforeend",r),u.refresh()}function y(){l.innerHTML="",u.refresh()}function b(){o&&(o.classList.add("is-active"),o.setAttribute("aria-hidden","false"))}function L(){o&&(o.classList.remove("is-active"),o.setAttribute("aria-hidden","true"))}function v(i){return i?i.replace(/[&<>"'`=\/]/g,r=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"})[r]):""}const w=document.getElementById("search-form"),A=document.getElementById("search-text");w.addEventListener("submit",E);function E(i){i.preventDefault();const r=A.value.trim();if(r===""){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}y(),b(),g(r).then(e=>{if(!e||!Array.isArray(e.hits)||e.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e.hits),n.success({title:"Success",message:`Found ${e.totalHits} images.`,position:"topRight"})}).catch(e=>{console.error("Error while fetching images:",e),n.error({title:"Request failed",message:"Something went wrong while fetching images. Please try again later.",position:"topRight"})}).finally(()=>{L()})}
//# sourceMappingURL=index.js.map
